def test_import_retry_and_source_deletion(page):
    page.get_by_role("link", name="知识库", exact=True).click()
    page.get_by_role("button", name="查看资料：早期讨论记录.pdf", exact=True).click()
    page.get_by_role("button", name="重新编译", exact=True).click()
    detail = page.get_by_role("complementary", name="资料详情")
    detail.get_by_text("已就绪", exact=True).wait_for()
    assert detail.get_by_text("已就绪", exact=True).is_visible()
    page.get_by_role("button", name="返回资料列表", exact=True).click()
    page.get_by_role("button", name="导入资料", exact=True).click()
    page.get_by_role("button", name="没有文件？使用示例文件体验", exact=False).click()
    page.get_by_role("button", name="开始导入", exact=True).click()
    source = page.get_by_role("button", name="查看资料：协作与设计原则.md", exact=True)
    source.wait_for()
    assert source.is_visible()
    page.get_by_role("button", name="移除资料", exact=True).click()
    page.get_by_role("button", name="保留资料", exact=True).click()
    assert source.is_visible()
    page.get_by_role("button", name="移除资料", exact=True).click()
    page.get_by_role("button", name="确认移除", exact=True).click()
    source.wait_for(state="detached")
    assert source.count() == 0


def test_page_edit_graph_and_quality(page):
    page.get_by_role("link", name="知识库", exact=True).click()
    page.get_by_role("tab", name="知识页面", exact=False).click()
    page.get_by_role("button", name="Agent 分层架构", exact=True).first.click()
    page.get_by_role("button", name="编辑页面", exact=True).click()
    page.get_by_role("textbox", name="知识页面正文").fill("## 验收记录\n重要结论保留来源。")
    page.get_by_role("button", name="保存页面", exact=True).click()
    assert page.get_by_role("heading", name="验收记录", exact=True).is_visible()
    page.get_by_role("button", name="返回知识页面列表", exact=True).click()
    page.get_by_role("tab", name="关联图谱", exact=True).click()
    page.get_by_role("button", name="插件运行时", exact=True).click()
    assert page.get_by_role("complementary", name="知识页面详情").get_by_role("heading", name="插件运行时", exact=True).is_visible()
    page.get_by_role("button", name="返回知识页面列表", exact=True).click()
    page.get_by_role("tab", name="质量检查", exact=True).click()
    page.get_by_role("button", name="运行示例检查", exact=True).click()
    page.get_by_role("button", name="修复失效引用", exact=True).click()
    assert page.get_by_text("已修复", exact=True).is_visible()


def test_new_empty_knowledge_base(page):
    page.get_by_role("link", name="知识库", exact=True).click()
    page.get_by_role("button", name="新建知识库", exact=True).click()
    page.get_by_role("textbox", name="知识库名称", exact=True).fill("验收知识库")
    page.get_by_role("button", name="创建知识库", exact=True).click()
    page.get_by_role("heading", name="从第一份资料开始", exact=True).wait_for()
    assert page.get_by_role("heading", name="从第一份资料开始", exact=True).is_visible()
