"""Add missing local Mem0 values to the ignored Agent .env file."""

from __future__ import annotations

from pathlib import Path
import secrets

from dotenv import dotenv_values


def main() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    env_file = repo_root / ".env"
    if not env_file.is_file():
        raise SystemExit("repository .env is missing")
    values = dotenv_values(env_file, interpolate=False)
    defaults = {
        "ICARUS_MEM0_API_KEY": secrets.token_urlsafe(32),
        "ICARUS_MEM0_POSTGRES_PASSWORD": secrets.token_urlsafe(32),
        "ICARUS_MEM0_JWT_SECRET": secrets.token_urlsafe(48),
        "ICARUS_MEM0_AUTH_DISABLED": "false",
        "ICARUS_MEM0_TELEMETRY": "false",
        "ICARUS_MEM0_OPENAI_BASE_URL": "https://api.deepseek.com",
        "ICARUS_MEM0_LLM_MODEL": "deepseek-v4-flash",
        "ICARUS_MEM0_EMBEDDER_PROVIDER": "fastembed",
        "ICARUS_MEM0_EMBEDDER_MODEL": (
            "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
        ),
        "ICARUS_MEM0_EMBEDDING_DIMS": "384",
    }
    additions = [
        f"{key}={value}"
        for key, value in defaults.items()
        if not values.get(key)
    ]
    if additions:
        with env_file.open("a", encoding="utf-8") as file:
            file.write("\n# Local Mem0 service (generated by Icarus)\n")
            file.write("\n".join(additions) + "\n")
    print("mem0-local-env-ready")


if __name__ == "__main__":
    main()
