"""Add missing local OpenKB settings without printing secret values."""

from pathlib import Path
import secrets

from dotenv import dotenv_values


def main() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    env_file = repo_root / ".env"
    if not env_file.is_file():
        raise SystemExit(f"Missing {env_file}; copy .example.env first.")
    values = dotenv_values(env_file, interpolate=False)
    additions: list[str] = []
    if not values.get("ICARUS_OPENKB_API_TOKEN"):
        additions.append("ICARUS_OPENKB_API_TOKEN=" + secrets.token_urlsafe(32))
    defaults = {
        "ICARUS_OPENKB_LLM_MODEL": "deepseek/deepseek-v4-flash",
        "ICARUS_OPENKB_OPENAI_BASE_URL": "https://api.deepseek.com",
    }
    additions.extend(
        f"{key}={value}" for key, value in defaults.items() if not values.get(key)
    )
    if additions:
        with env_file.open("a", encoding="utf-8") as file:
            file.write("\n# Local OpenKB service (generated by Icarus)\n")
            file.write("\n".join(additions) + "\n")
    print("openkb-local-env-ready")


if __name__ == "__main__":
    main()
